language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn elm-install

script:
    - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master